#!/bin/bash
set -e

create_issue() {
  local title="$1"
  local body="$2"
  local labels="$3"
  gh issue create --title "$title" --body "$body" --label "$labels" --repo unixfundz/stellar-sim
}

# Create labels first
gh label create "good first issue" --color "7057ff" --description "Good for newcomers" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "help wanted" --color "008672" --description "Extra attention needed" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "core" --color "e4e669" --description "Core functionality" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "cli" --color "0075ca" --description "CLI related" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "wasm" --color "e99695" --description "WASM related" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "soroban" --color "f9d0c4" --description "Soroban related" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "diagnostics" --color "c5def5" --description "Diagnostics related" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "testing" --color "bfd4f2" --description "Testing related" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "documentation" --color "d4c5f9" --description "Documentation" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "ci" --color "0052cc" --description "CI/CD related" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "performance" --color "e4e669" --description "Performance related" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "ledger" --color "f9d0c4" --description "Ledger related" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "output" --color "c5def5" --description "Output related" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "network" --color "bfd4f2" --description "Network related" --repo unixfundz/stellar-sim 2>/dev/null || true
gh label create "security" --color "d93f0b" --description "Security related" --repo unixfundz/stellar-sim 2>/dev/null || true

echo "Labels created. Creating issues..."

create_issue "Add --version flag to CLI" "Add \`--version\` support so \`stellar-sim --version\` prints the crate version and exits.\n\n**Acceptance criteria:**\n- \`stellar-sim --version\` prints \`stellar-sim x.y.z\`\n- Test asserts output contains version string" "good first issue,cli"
create_issue "Add --help descriptions to all CLI subcommands" "All subcommands are missing descriptive help text.\n\n**Acceptance criteria:**\n- All subcommands have \`about\` text\n- All flags have \`help\` text\n- PR includes sample \`--help\` output" "good first issue,cli,documentation"
create_issue "Add license headers to all source files" "All \`.rs\` files must have SPDX license headers.\n\n\`\`\`rust\n// Copyright 2025 stellar-sim contributors\n// SPDX-License-Identifier: Apache-2.0\n\`\`\`\n\n**Acceptance criteria:**\n- All \`.rs\` files have the header\n- CI check script added" "good first issue,ci"
create_issue "Set up GitHub Actions CI workflow" "Create \`.github/workflows/ci.yml\` running \`cargo fmt --check\`, \`cargo clippy\`, and \`cargo test\` on every PR.\n\n**Acceptance criteria:**\n- Workflow passes on clean build\n- README badge added" "good first issue,ci"
create_issue "Add --quiet flag to suppress non-essential output" "When \`--quiet\` is passed, only errors and final results should be printed.\n\n**Acceptance criteria:**\n- \`--quiet\` flag accepted globally\n- Verbose output suppressed\n- Test verifies output difference" "good first issue,cli"
create_issue "Implement inspect subcommand -- list WASM exports" "Load a \`.wasm\` file and print all exported function names.\n\n**Expected output:**\n\`\`\`\nExports:\n  - transfer\n  - balance\n\`\`\`\n\n**Acceptance criteria:**\n- Lists exports for a sample contract\n- Error if file is not valid WASM\n- Unit test with minimal WASM binary" "good first issue,wasm"
create_issue "Add --output flag to write simulation results to a file" "Allow users to redirect simulation output to a file with \`--output results.json\`.\n\n**Acceptance criteria:**\n- Results written to file when flag provided\n- Default stdout behaviour unchanged\n- Test verifies file content" "good first issue,cli"
create_issue "Add colour support to CLI output" "Use the \`colored\` crate to highlight errors in red, success in green, warnings in yellow.\n\n**Acceptance criteria:**\n- Errors are red, success is green\n- Colour disabled when \`NO_COLOR\` env var is set" "good first issue,cli"
create_issue "Add CHANGELOG.md with initial entry" "Create a \`CHANGELOG.md\` following Keep a Changelog format.\n\n**Acceptance criteria:**\n- Follows https://keepachangelog.com format\n- Includes initial feature list" "good first issue,documentation"
create_issue "Add .gitignore for Rust projects" "Add a comprehensive \`.gitignore\` covering \`target/\`, editor files, and OS files.\n\n**Acceptance criteria:**\n- Rust build artifacts ignored\n- Editor files ignored\n- OS files ignored" "good first issue"

echo "Issues 1-10 created..."

create_issue "Document all public functions with doc comments" "Every \`pub fn\` must have a \`///\` doc comment.\n\n**Acceptance criteria:**\n- \`cargo doc --no-deps\` produces no warnings\n- All public functions documented" "good first issue,documentation"
create_issue "Add --dry-run flag to simulate subcommand" "When \`--dry-run\` is passed, validate inputs without actually running simulation.\n\n**Acceptance criteria:**\n- Validates WASM file exists\n- Prints summary of what would run\n- No simulation actually runs" "good first issue,cli"
create_issue "Add inspect subcommand -- list WASM imports" "Extend \`inspect\` to list all imported functions.\n\n**Expected output:**\n\`\`\`\nImports:\n  - env::log_str\n\`\`\`\n\n**Acceptance criteria:**\n- Imports listed separately from exports\n- Test with sample WASM binary" "good first issue,wasm"
create_issue "Add error exit codes to CLI" "Different errors should return distinct exit codes.\n\n- \`0\` success\n- \`1\` general error\n- \`2\` invalid arguments\n- \`3\` WASM not found\n- \`4\` simulation failed\n\n**Acceptance criteria:**\n- Exit codes documented\n- Tests verify each code" "good first issue,cli"
create_issue "Add --timeout flag to simulation" "Allow \`--timeout 5000\` to set maximum execution time in milliseconds.\n\n**Acceptance criteria:**\n- Simulation aborts if timeout exceeded\n- Clear error message\n- Default timeout of 30 seconds" "good first issue,cli"
create_issue "Add progress spinner for long-running simulations" "Show a spinner using \`indicatif\` crate while simulation runs.\n\n**Acceptance criteria:**\n- Spinner appears during simulation\n- Stops on completion\n- Hidden when \`--quiet\` is set" "good first issue,cli"
create_issue "Validate WASM magic bytes before simulation" "Check the file starts with WASM magic bytes (\`\\0asm\`) before parsing.\n\n**Acceptance criteria:**\n- Clear error for non-WASM files\n- Clear error for empty files\n- Unit test with invalid input" "good first issue,wasm"
create_issue "Add --network flag to select testnet/mainnet presets" "Allow \`--network testnet\` or \`--network mainnet\` to pre-configure RPC endpoints.\n\n**Acceptance criteria:**\n- Both presets defined\n- Custom RPC still overridable\n- Test verifies correct URL selected" "good first issue,cli,network"
create_issue "Create issue and PR templates for GitHub" "Add \`.github/ISSUE_TEMPLATE/bug_report.md\`, \`feature_request.md\`, and \`PULL_REQUEST_TEMPLATE.md\`.\n\n**Acceptance criteria:**\n- Bug report includes reproduction steps\n- Feature request includes motivation\n- PR template has checklist" "good first issue,documentation"
create_issue "Add --no-color flag as alias for NO_COLOR env var" "Allow \`--no-color\` as a CLI flag.\n\n**Acceptance criteria:**\n- \`--no-color\` disables ANSI colour\n- Works alongside \`NO_COLOR\` env var\n- Test verifies plain output" "good first issue,cli"

echo "Issues 11-20 created..."

create_issue "Print CPU and memory usage after every simulation" "Always print CPU instructions and memory bytes after simulation.\n\n**Expected output:**\n\`\`\`\nCPU instructions: 504,211\nMemory bytes:     1,024\n\`\`\`\n\n**Acceptance criteria:**\n- Stats always shown\n- Numbers formatted with thousands separators\n- Hidden with \`--quiet\`" "good first issue,output"
create_issue "Add --args-file flag to read arguments from JSON file" "Allow \`--args-file args.json\` as alternative to inline \`--args\`.\n\n**Acceptance criteria:**\n- Reads JSON array from file\n- Error if file not found or invalid JSON\n- Test with sample args file" "good first issue,cli"
create_issue "Add basic logging with tracing crate" "Add structured logging using \`tracing\` controlled by \`RUST_LOG\`.\n\n**Acceptance criteria:**\n- \`RUST_LOG=info\` shows high-level steps\n- \`RUST_LOG=debug\` shows detailed info\n- Logs go to stderr" "good first issue"
create_issue "Add --contract-id flag to simulate subcommand" "Allow \`--contract-id GABC...\` to specify contract ID for simulation context.\n\n**Acceptance criteria:**\n- Contract ID passed to host\n- Validated as valid Stellar account ID\n- Test with valid and invalid IDs" "good first issue,cli"
create_issue "Create a Makefile with common development tasks" "Add \`Makefile\` with targets: \`build\`, \`test\`, \`lint\`, \`fmt\`, \`clean\`, \`docs\`.\n\n**Acceptance criteria:**\n- All targets work\n- \`make help\` lists targets\n- Documented in README" "good first issue"
create_issue "Add --fn as short alias for --function flag" "Add \`--fn\` as a short alias for \`--function\` in the simulate subcommand.\n\n**Acceptance criteria:**\n- Both \`--fn\` and \`--function\` accepted\n- Help text shows both\n- Test uses short form" "good first issue,cli"
create_issue "Implement summary table renderer for batch results" "Implement \`render_summary_table(results: &[SimResult])\` with columns: Function, Status, CPU, Memory.\n\n**Acceptance criteria:**\n- Table renders correctly\n- Unit test with sample data" "good first issue,output"
create_issue "Add --env flag to set environment variables for simulation" "Allow \`--env KEY=VALUE\` to inject environment variables.\n\n**Acceptance criteria:**\n- Multiple \`--env\` flags accepted\n- Variables passed to host\n- Test verifies injection" "good first issue,cli"
create_issue "Add inspect subcommand -- show WASM file size and section breakdown" "Show total file size and size of each WASM section.\n\n**Expected output:**\n\`\`\`\nFile size: 14.2 KB\nSections:\n  code: 8.1 KB\n\`\`\`\n\n**Acceptance criteria:**\n- Sizes in human-readable format\n- Test with known WASM file" "good first issue,wasm"
create_issue "Add --max-memory flag to cap memory usage" "Allow \`--max-memory 512000\` to set maximum memory in bytes.\n\n**Acceptance criteria:**\n- Memory limit passed to host\n- Simulation aborts with clear error if exceeded\n- Default limit documented" "good first issue,cli"

echo "Issues 21-30 created..."

create_issue "Decode diagnostic events into human-readable output" "The \`events\` subcommand should decode base64 XDR DiagnosticEvents into plain English.\n\n**Expected output:**\n\`\`\`\nEvent #1\n  Type:     diagnostic\n  Contract: GABC...\n  Topics:   [\"transfer\"]\n  Data:     \"100\"\n\`\`\`\n\n**Acceptance criteria:**\n- Correctly decodes sample XDR\n- Graceful error on malformed input\n- Integration test" "help wanted,diagnostics,soroban"
create_issue "Add JSON output mode to simulate subcommand" "Add \`--json\` flag for structured JSON output.\n\n**Expected output:**\n\`\`\`json\n{\"success\": true, \"cpu_instructions\": 504211}\n\`\`\`\n\n**Acceptance criteria:**\n- \`--json\` produces valid JSON\n- Plain text unchanged without flag\n- Both modes tested" "help wanted,cli,output"
create_issue "Load ledger snapshot from JSON file" "Accept \`--ledger snapshot.json\` to populate host storage before simulation.\n\n**Format:**\n\`\`\`json\n{\"entries\": [{\"key\": \"<base64>\", \"value\": \"<base64>\"}]}\n\`\`\`\n\n**Acceptance criteria:**\n- Entries loaded correctly\n- Clear errors for malformed entries\n- Test with at least one entry" "help wanted,ledger,soroban"
create_issue "Implement contract_id_to_hex helper function" "Implement \`contract_id_to_hex(id: &Hash) -> String\` converting raw contract hash to hex.\n\n**Acceptance criteria:**\n- Returns correct hex encoding\n- Used in event display\n- Unit tests with known inputs" "help wanted,soroban"
create_issue "Implement scval_to_xdr_base64 helper function" "Implement \`scval_to_xdr_base64(val: &ScVal) -> String\` serializing ScVal to base64 XDR.\n\n**Acceptance criteria:**\n- Correctly encodes common ScVal types\n- Round-trip test\n- Unit tests" "help wanted,soroban"
create_issue "Add WASM validation step before simulation" "Validate WASM binary for Soroban compatibility before running.\n\n**Acceptance criteria:**\n- Float contracts rejected with clear message\n- SIMD contracts rejected\n- Valid contracts pass through" "help wanted,wasm"
create_issue "Implement batch simulation from JSON manifest" "Add \`simulate --batch manifest.json\` to run multiple calls in sequence.\n\n**Format:**\n\`\`\`json\n[{\"function\": \"transfer\", \"args\": [\"GABC\", \"GXYZ\", \"100\"]}]\n\`\`\`\n\n**Acceptance criteria:**\n- All invocations run in order\n- Results shown as table\n- One failure does not stop batch" "help wanted,cli"
create_issue "Add --assert-return flag to validate return value" "Allow \`--assert-return \"100\"\` to fail if return value doesn't match.\n\n**Acceptance criteria:**\n- Exit 0 when return matches\n- Exit 1 when it does not\n- Useful in CI scripts" "help wanted,testing"
create_issue "Format ScVal return values as human-readable strings" "Decode return values and display in human-readable format.\n\n**Examples:**\n- \`ScVal::I64(42)\` → \`42 (i64)\`\n- \`ScVal::Symbol(\"transfer\")\` → \`\"transfer\" (symbol)\`\n\n**Acceptance criteria:**\n- All common variants handled\n- Fallback to hex for unknown types\n- Unit tests for each variant" "help wanted,output,soroban"
create_issue "Add --ledger-sequence flag to set simulated ledger sequence" "Allow \`--ledger-sequence 1234567\` to set the ledger sequence in simulation context.\n\n**Acceptance criteria:**\n- Sequence set on host before execution\n- Contracts reading ledger sequence reflect value\n- Test verifies accessibility" "help wanted,ledger"

echo "Issues 31-40 created..."

create_issue "Implement extract_wasm_instruction for diagnostic output" "Extract WASM instruction name from diagnostic event data for tick/budget topics.\n\n**Acceptance criteria:**\n- Correctly extracts from \`Instruction: i32.add\` pattern\n- Returns None when not found\n- Unit tests" "help wanted,wasm,diagnostics"
create_issue "Add --fee-limit flag to cap transaction fee" "Allow \`--fee-limit 10000\` to set maximum fee in stroops.\n\n**Acceptance criteria:**\n- Fee limit passed to simulation\n- Estimated fee reported\n- Warning if estimated exceeds limit" "help wanted,cli"
create_issue "Implement decode_error for human-readable VM errors" "Map raw Soroban/WASM error strings to clear English descriptions.\n\n**Examples:**\n- \`wasm trap: out of bounds\` → \`VM Trap: Out of Bounds Access\`\n- \`integer overflow\` → \`VM Trap: Integer Overflow\`\n\n**Acceptance criteria:**\n- All common VM trap types handled\n- Fallback returns raw message\n- Unit tests" "help wanted,diagnostics"
create_issue "Add --resource-calibration flag to tune resource limits" "Allow passing a JSON resource calibration config to tune CPU and memory limits.\n\n**Acceptance criteria:**\n- JSON config parsed and applied\n- Invalid config produces clear error\n- Documented with example" "help wanted,cli,soroban"
create_issue "Implement extract_missing_key_id for storage errors" "Extract ledger key ID from HostError strings to produce useful error messages.\n\n**Acceptance criteria:**\n- Correctly extracts from \`LedgerKey(ContractData(...))\` pattern\n- Returns None when not found\n- Unit tests" "help wanted,diagnostics,soroban"
create_issue "Add --auth flag to provide authorisation entries" "Allow \`--auth auth.json\` to provide base64 XDR auth entries.\n\n**Acceptance criteria:**\n- Auth entries loaded and passed to host\n- Test with contract requiring auth\n- Clear error if malformed" "help wanted,cli,soroban"
create_issue "Generate LCOV coverage report from simulation" "Write LCOV report showing which WASM functions were invoked.\n\n**Acceptance criteria:**\n- LCOV file written to \`--coverage-output\` path\n- Report includes SF, FN, FNDA records\n- Test verifies function hit counts" "help wanted,testing"
create_issue "Add --footprint flag to display transaction footprint" "Display read/write footprint after simulation.\n\n**Expected output:**\n\`\`\`\nFootprint:\n  Read:  ContractData(GABC..., \"balance\")\n  Write: ContractData(GABC..., \"balance\")\n\`\`\`\n\n**Acceptance criteria:**\n- Footprint displayed after simulation\n- Shown in JSON when \`--json\` set\n- Test with contract that reads and writes" "help wanted,soroban"
create_issue "Add --print-auth flag to display required auth entries" "Display auth entries required to submit the transaction.\n\n**Acceptance criteria:**\n- Auth entries printed in base64 XDR\n- Decoded when \`--verbose\` is set\n- Test with contract requiring auth" "help wanted,soroban"
create_issue "Add --source-account flag to set transaction source" "Allow \`--source-account GABC...\` to set source account.\n\n**Acceptance criteria:**\n- Source account set on context\n- Validated as Stellar account ID\n- Test verifies accessibility" "help wanted,cli"

echo "Issues 41-50 created..."

create_issue "Implement wipe_ledger_state on SimHost" "Add \`wipe_ledger_state()\` method resetting all storage to empty.\n\n**Acceptance criteria:**\n- Storage cleared after wipe\n- Host remains functional\n- Test verifies state gone" "help wanted,soroban"
create_issue "Add support for reading WASM from stdin" "Allow \`-\` as value for \`--wasm\` to read WASM from stdin.\n\n**Acceptance criteria:**\n- Piped input works\n- Error if stdin empty\n- Test using piped input" "help wanted,cli,wasm"
create_issue "Add --verbose flag for detailed execution trace" "When \`--verbose\` is set, print step-by-step execution trace.\n\n**Acceptance criteria:**\n- Each host function call logged\n- Return values shown\n- Output clearly formatted" "help wanted,cli,diagnostics"
create_issue "Implement simulate for invoke_contract operation type" "Add support for simulating \`invoke_contract\` XDR operations directly.\n\n**Acceptance criteria:**\n- \`--operation <base64-xdr>\` flag accepted\n- Operation decoded and simulated\n- Test with sample operation XDR" "help wanted,soroban"
create_issue "Add --events-only flag to suppress non-event output" "When \`--events-only\` set, print only diagnostic events.\n\n**Acceptance criteria:**\n- Only events printed\n- Compatible with \`--json\`\n- Test verifies suppressed output" "help wanted,cli,output"
create_issue "Implement SourceMapper for WASM debug symbols" "Map WASM offsets to source locations using DWARF debug info.\n\n**Acceptance criteria:**\n- Source file and line shown when available\n- Falls back to offset when no symbols\n- Test with WASM with and without debug info" "help wanted,wasm"
create_issue "Add --assert-cpu-limit flag for performance testing" "Allow \`--assert-cpu-limit 500000\` to fail if CPU usage exceeds value.\n\n**Acceptance criteria:**\n- Exit 0 if within limit\n- Exit 1 with message if over\n- Useful for CI regression testing" "help wanted,testing,performance"
create_issue "Add --repeat flag to run simulation N times and report averages" "Allow \`--repeat 10\` to run simulation multiple times and report min/max/avg.\n\n**Acceptance criteria:**\n- Table shows min, max, avg for CPU and memory\n- All runs use identical inputs\n- Test with at least 3 repetitions" "help wanted,performance"
create_issue "Add --compare flag to diff two simulation results" "Compare results of two runs: \`stellar-sim compare --before before.json --after after.json\`.\n\n**Acceptance criteria:**\n- Differences highlighted\n- CPU and memory delta shown\n- Return value diff shown" "help wanted,output"
create_issue "Implement snapshot subcommand to save ledger state" "Save ledger entries for a contract to a JSON file.\n\n**Usage:**\n\`\`\`\nstellar-sim snapshot --rpc https://... --contract GABC... --output snapshot.json\n\`\`\`\n\n**Acceptance criteria:**\n- Downloads and serializes entries\n- Output compatible with \`--ledger\`\n- Handles RPC errors" "help wanted,ledger,network"

echo "Issues 51-60 created..."

create_issue "Add --ledger-timestamp flag to set simulated timestamp" "Allow \`--ledger-timestamp 1700000000\` to set simulated ledger close time.\n\n**Acceptance criteria:**\n- Timestamp set before execution\n- Contracts reading timestamp reflect value\n- Test verifies accessibility" "help wanted,ledger"
create_issue "Add --min-temp-entry-expiry and --min-persistent-entry-expiry flags" "Configure entry expiration settings for simulation context.\n\n**Acceptance criteria:**\n- Both flags accepted and applied\n- Documented with sensible defaults\n- Test verifies expiry affects simulation" "help wanted,ledger,soroban"
create_issue "Add --print-return-xdr flag to print raw return value XDR" "Print base64-encoded XDR of return value alongside decoded version.\n\n**Acceptance criteria:**\n- Raw XDR printed when flag set\n- Shown as \`return_value_xdr\` in JSON\n- Test verifies XDR round-trips" "help wanted,output"
create_issue "Implement categorize_events function" "Implement function categorising HostEvents into CategorizedEvents with type labels.\n\n**Acceptance criteria:**\n- Contract, System, Diagnostic events categorised correctly\n- \`event_type\` is lowercase string\n- \`in_successful_contract_call\` is negation of \`failed_call\`\n- Unit tests for all three types" "help wanted,diagnostics,soroban"
create_issue "Add rate limiting to RPC calls in snapshot subcommand" "Throttle RPC requests with configurable delays.\n\n**Acceptance criteria:**\n- \`--rpc-delay-ms\` flag accepted\n- Requests throttled accordingly\n- Retry logic for 429 responses" "help wanted,network"
create_issue "Add --wasm-cache flag to cache compiled WASM between runs" "Cache compiled WASM module to disk for faster repeated simulations.\n\n**Acceptance criteria:**\n- Cache stored in \`~/.stellar-sim/cache/\`\n- Keyed by WASM file hash\n- \`--no-cache\` flag to bypass" "help wanted,performance,wasm"
create_issue "Add --print-events-on-failure flag" "When simulation fails, automatically print all diagnostic events.\n\n**Acceptance criteria:**\n- Events printed automatically on failure\n- Clearly labelled as failure diagnostics\n- Test with contract that fails and emits events" "help wanted,diagnostics,output"
create_issue "Implement --simulate-auth-checks flag" "Enable strict authorisation checking during simulation.\n\n**Acceptance criteria:**\n- Auth failures produce clear error messages\n- \`--skip-auth\` disables checks\n- Test with contract requiring specific signer" "help wanted,soroban"
create_issue "Add --print-storage-diff to show storage changes after simulation" "Print which storage entries were created, modified, or deleted.\n\n**Expected output:**\n\`\`\`\nStorage diff:\n  CREATED: ContractData(GABC..., \"counter\") = 1\n  MODIFIED: ContractData(GABC..., \"balance\") = 900 (was 1000)\n\`\`\`\n\n**Acceptance criteria:**\n- Created, modified, deleted entries shown\n- JSON output supported" "help wanted,ledger,output"
create_issue "Write end-to-end integration test for simulate" "Write integration test compiling a minimal Soroban adder contract and asserting correct return value.\n\n**Acceptance criteria:**\n- Compiles real \`.wasm\` file\n- Asserts return value matches expected\n- CPU instructions within reasonable range\n- Runs in CI" "help wanted,testing"

echo "Issues 61-70 created..."

create_issue "Implement full SimHost with Soroban host integration" "Implement \`SimHost::new()\` with full host initialisation: budget, storage, diagnostic level, module cache.\n\n**Acceptance criteria:**\n- Host initialised with correct defaults\n- \`memory_limit\` wired through\n- Integration test runs real contract" "core,soroban"
create_issue "Implement execute_operations function" "Implement core function executing XDR operations against the host.\n\n**Acceptance criteria:**\n- All operation types handled\n- Returns result with budget usage\n- Errors translated to human-readable messages" "core,soroban"
create_issue "Add coverage tracking with CoverageTracker" "Implement \`CoverageTracker\` tracking invoked WASM functions and call counts.\n\n**Acceptance criteria:**\n- \`invoked_functions: HashMap<String, u64>\` tracks counts\n- Updated during execution\n- Unit tests verify counts" "core,testing"
create_issue "Implement generate_lcov_report function" "Implement \`generate_lcov_report(coverage: &CoverageTracker, wasm_path: &str) -> String\`.\n\n**Acceptance criteria:**\n- Output parseable by lcov tooling\n- Includes SF, FN, FNDA, FNF, FNH records\n- Test verifies function hit counts" "core,testing"
create_issue "Implement enforce_soroban_compatibility WASM validator" "Reject WASM binaries using floats, SIMD, or unsupported features.\n\n**Acceptance criteria:**\n- Float instructions rejected\n- SIMD rejected\n- Valid contracts pass\n- Unit tests for each case" "core,wasm,security"
create_issue "Implement wipe_ledger_state_preserving_modules on SimHost" "Reset host storage while preserving module cache.\n\n**Acceptance criteria:**\n- Storage cleared\n- Module cache preserved\n- Host executable after wipe\n- Test verifies state gone but modules intact" "core,soroban"
create_issue "Implement SourceMapper for WASM offset to source location mapping" "Read DWARF debug info and map byte offsets to source file/line.\n\n**Acceptance criteria:**\n- \`map_wasm_offset_to_source(offset) -> Option<SourceLocation>\`\n- Returns None without debug symbols\n- Test with WASM with and without debug info" "core,wasm"
create_issue "Implement panic-safe execution wrapper" "Wrap contract execution in \`std::panic::catch_unwind\`.\n\n**Acceptance criteria:**\n- Panics caught and returned as errors\n- Simulator does not crash\n- Error includes panic message\n- Test with contract that panics" "core,soroban,security"
create_issue "Add support for TxFeeBump transaction envelope" "Handle \`TransactionEnvelope::TxFeeBump\` unwrapping the inner transaction.\n\n**Acceptance criteria:**\n- FeeBump envelope unwrapped correctly\n- Inner operations extracted\n- Test with FeeBump XDR" "core,soroban"
create_issue "Implement extract_wasm_offset from error messages" "Implement \`extract_wasm_offset(error_msg: &str) -> Option<u64>\` finding hex offsets in error strings.\n\n**Acceptance criteria:**\n- Correctly extracts offset from Soroban/Wasmi errors\n- Returns None when absent\n- Unit tests with sample strings" "core,diagnostics"

echo "Issues 71-80 created..."

create_issue "Implement full XDR transaction simulation pipeline" "End-to-end simulation from base64 XDR TransactionEnvelope to structured result.\n\n**Acceptance criteria:**\n- Decodes envelope, extracts operations, executes, returns result\n- Handles V0, V1, FeeBump envelopes\n- Integration test with real XDR" "core,soroban"
create_issue "Add LLVM SanitizerCoverage harness support" "Add build support for LLVM SanitizerCoverage for fuzz testing coverage.\n\n**Acceptance criteria:**\n- \`--enable-coverage\` build flag added\n- Coverage harness compiles cleanly\n- CI workflow runs coverage build" "core,ci"
create_issue "Implement init_logger with JSON and text format support" "Implement \`init_logger()\` reading \`ERST_LOG_FORMAT\` env var and configuring tracing_subscriber.\n\n**Acceptance criteria:**\n- \`ERST_LOG_FORMAT=json\` produces JSON logs\n- Default produces human-readable text\n- Logs go to stderr" "core"
create_issue "Implement error serialisation to stdout JSON for IPC" "Write structured JSON error to stdout on simulation failure.\n\n**Format:**\n\`\`\`json\n{\"status\": \"error\", \"error\": \"VM Trap: Out of Bounds\"}\n\`\`\`\n\n**Acceptance criteria:**\n- All error paths produce valid JSON\n- Non-zero exit always accompanies error\n- Test verifies format" "core,output"
create_issue "Add fuzz target for XDR event decoding" "Add cargo-fuzz target feeding random bytes to event decoder.\n\n**Acceptance criteria:**\n- Fuzz target compiles with \`cargo fuzz build\`\n- No panics on arbitrary input\n- Added to CI fuzz job" "core,security,testing"
create_issue "Implement snapshot RPC client using reqwest" "Implement HTTP client calling Stellar RPC \`getLedgerEntries\` endpoint.\n\n**Acceptance criteria:**\n- Correct RPC request format\n- Handles pagination\n- Retries on transient errors" "core,network"
create_issue "Add support for contract-to-contract calls in simulation" "Ensure simulator handles contracts invoking other contracts.\n\n**Acceptance criteria:**\n- Sub-invocations execute correctly\n- Events from sub-calls included\n- Test with two contracts where one calls the other" "core,soroban"
create_issue "Implement --coverage-diff to compare coverage between two runs" "Compare two LCOV files and show which functions gained or lost coverage.\n\n**Acceptance criteria:**\n- New, removed, changed functions shown\n- Delta in hit counts displayed\n- JSON output supported" "core,testing"
create_issue "Add signature_verification_mock module" "Implement mock signature verifier approving all signatures during simulation.\n\n**Acceptance criteria:**\n- Mock accepts any signature\n- Enabled via \`--mock-signatures\` flag\n- Real verification remains default\n- Test verifies mock behaviour" "core,soroban,testing"
create_issue "Implement --strict-vm flag for protocol-21 VM enforcement" "Add \`--strict-vm\` enabling \`vm::enforce_soroban_compatibility\` before execution.\n\n**Acceptance criteria:**\n- Float contracts rejected in strict mode\n- Non-strict mode allows them\n- Test with compliant and non-compliant contracts" "core,soroban,security"

echo "Issues 81-90 created..."

create_issue "Add Windows CI support to GitHub Actions" "Add Windows runner to GitHub Actions matrix.\n\n**Acceptance criteria:**\n- \`windows-latest\` added to CI matrix\n- All tests pass on Windows\n- Path separator issues handled" "core,ci"
create_issue "Implement --flamegraph flag to generate CPU flamegraph" "Generate flamegraph SVG showing call stack and CPU breakdown.\n\n**Acceptance criteria:**\n- SVG written to \`--flamegraph-output\` path\n- Uses \`inferno\` crate\n- Test verifies valid SVG output" "core,performance"
create_issue "Add --profile flag for benchmark profiling mode" "Run simulation with extra instrumentation measuring time per host function.\n\n**Acceptance criteria:**\n- Per-host-function timing collected\n- Sorted by time consumed\n- JSON and table output supported" "core,performance"
create_issue "Implement cross-platform binary distribution via GitHub Releases" "Build binaries for Linux, macOS, and Windows on tag push.\n\n**Acceptance criteria:**\n- Binaries built for all platforms\n- Attached to GitHub Release automatically\n- SHA256 checksums included" "core,ci"
create_issue "Add --ipc mode for embedding stellar-sim as subprocess" "Add IPC mode reading JSON requests from stdin and writing responses to stdout.\n\n**Protocol:**\n\`\`\`json\n{\"action\": \"simulate\", \"function\": \"transfer\", \"args\": []}\n\`\`\`\n\n**Acceptance criteria:**\n- Handles multiple sequential requests\n- Errors returned as JSON\n- Test client provided" "core"
create_issue "Implement --gas-estimation mode" "Run simulation multiple times with increasing limits to estimate minimum required fee.\n\n**Acceptance criteria:**\n- Returns minimum CPU, memory, and fee\n- Uses binary search for efficiency\n- Results in human-readable and JSON format" "core,soroban"
create_issue "Add --state-expiry-simulation flag" "Simulate state expiry by marking specified entries as expired before execution.\n\n**Acceptance criteria:**\n- Specified entries marked expired\n- Contract behaviour on expired state tested\n- Clear error messages" "core,soroban,ledger"
create_issue "Implement structured test harness for contract unit testing" "Build \`stellar-sim-test\` library for contract developers to write unit tests.\n\n**Acceptance criteria:**\n- \`SimTestEnv::new()\` creates isolated test environment\n- \`invoke(fn, args)\` runs function and returns result\n- \`assert_event(...)\` checks emitted events\n- Published as separate crate" "core,testing"
create_issue "Add Prometheus metrics endpoint for monitoring" "Expose \`/metrics\` endpoint in Prometheus format when run with \`--serve\`.\n\n**Acceptance criteria:**\n- Valid Prometheus text format\n- Counter for total simulations\n- Histogram for CPU instructions\n- Error rate counter" "core,network"
create_issue "Publish stellar-sim to crates.io" "Prepare crate for publication: complete metadata, docs, examples, publish workflow.\n\n**Acceptance criteria:**\n- \`cargo publish --dry-run\` succeeds\n- \`cargo doc\` produces complete docs\n- At least two runnable examples\n- Automated publish on version tag" "core,documentation"

echo "All 100 issues created!"
